name: "infra preview & deploy"

on:
  push:
    branches:
      - main
    paths:
      - 10_infra/**
      - .github/workflows/**
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-northeast-1
  TF_VERSION: 1.12.1
  TF_PROJECT: tastylog
  TF_ENVIRONMENT: dev

defaults: 
  run:
    shell: bash
    working-directory: "10_infra/"

jobs:
  preview:
    name: "Preview"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Check Terraform Version
        run: terraform --version

      - name: Terraform format
        run: |
          terraform fmt -check
      - name: Configure AWS credential
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}

      - name: Terraform init
        run: |
          #mkdir -p ~/.aws
          #echo "[profile terraform]" >> ~/.aws/config
          #echo "region = $AWS_REGION" >> ~/.aws/config
          #echo "output = json" >> ~/.aws/config
          #aws configure list-profiles
          #export AWS_PROFILE=terraform
          #aws sts get-caller-identity
          #aws s3 ls s3://dntnbucket002
          #TF_LOG=DEBUG terraform init -no-color
          terraform init -no-color
      
      - name: Terraform validate
        run: |
          terraform validate -no-color

      - name: Terraform plan
        run: |
        　aws iam list-attached-role-policies --role-name app_iam_role 
          terraform plan \
            -var 'project=${{ env.TF_PROJECT }}' \
            -var 'environment=${{ env.TF_ENVIRONMENT }}' \
            -var 'username=${{ secrets.MYSQL_USERNAME }}' \
            -var 'password=${{ secrets.MYSQL_PASSWORD }}' \
            -input=false \
            -no-color \
            -detailed-exitcode