name: "infra preview & deploy"

on:
  push:
    branches:
      - main
    paths:
      - 10_infra/**
      - .github/workflows/**
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-northeast-1
  TF_VERSION: 1.12.1

defaults: 
  run:
    shell: bash
    working-directory: "10_infra/"

jobs:
  preview:
    name: "Preview"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Check Terraform Version
        run: terraform --version

      - name: Terraform format
        run: |
          terraform fmt -check
      - name: Configure AWS credential
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}

      - name: Set AWS Profile
        run: echo "AWS_PROFILE=terraform" >> $GITHUB_ENV

      - name: Terraform init
        run: |
          echo "AWS_PROFILE=$AWS_PROFILE"
          echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID"
          echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY"
          mkdir -p ~/.aws
          echo "[profile terraform]" >> ~/.aws/config
          echo "region = $AWS_REGION" >> ~/.aws/config
          echo "output = json" >> ~/.aws/config
          echo "[terraform]" >> ~/.aws/credentials
          echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
          echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
          echo "region = $AWS_REGION" >> ~/.aws/credentials
          aws configure list-profiles
          cat ~/.aws/config
          cat ~/.aws/credentials
          aws sts get-caller-identity --profile terraform
          aws s3 ls s3://dntnbucket002 --profile terraform
          TF_LOG=DEBUG terraform init -no-color


          