name: "z Slack Notify"

on:
  workflow_dispatch:

jobs:
  notify:
    name: Slack notify
    runs-on: ubuntu-latest
    steps:
      - name: Slack notify
        uses: slackapi/slack-github-action@v2.1.0
        with:
          channel-id: "C090JHN29TL"
          payload: |
            {
              "attachments": [
                {
                  "blocks": [
                    {
                      "type": "header",
                      "text": {
                        "type": "plain_text",
                        "text": "Message Header",
                        "emoji": true
                      }
                    },
                    {
                      "type": "section",
                        "text": {
                        "type": "mrkdwn",
                        "text": "Hellow World :ghost:"
                      }
                    }
                  ]
                }
              ]
            }
        env: 
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}